// portfolio-react/src/components/Sidebar.tsx
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import './Sidebar.css'

const Sidebar = () => {
  const [isCollapsed, setIsCollapsed] = useState(false)
  const location = useLocation()

  const toggleSidebar = () => {
    setIsCollapsed(!isCollapsed)
  }

  const isActive = (path: string) => {
    if (path === '/' && location.pathname === '/') return true
    if (path !== '/' && location.pathname.startsWith(path)) return true
    return false
  }

  return (
    <nav className={`sidebar ${isCollapsed ? 'collapsed' : ''}`}>
      <div className="sidebar-header">
        <div className="logo">
          <i className="fas fa-snowflake"></i>
          <span>Good day, visitor!</span>
        </div>
        <button 
          className="sidebar-toggle" 
          onClick={toggleSidebar}
          aria-label="Toggle sidebar"
        >
          <i className={`fas fa-chevron-left ${isCollapsed ? 'rotated' : ''}`}></i>
        </button>
      </div>
      
      <ul className="nav-menu">
        <li className="nav-item">
          <Link 
            to="/" 
            className={`nav-link ${isActive('/') ? 'active' : ''}`}
          >
            <i className="fas fa-home"></i>
            <span>Home</span>
          </Link>
        </li>
        <li className="nav-item">
          <Link 
            to="/about" 
            className={`nav-link ${isActive('/about') ? 'active' : ''}`}
          >
            <i className="fas fa-user"></i>
            <span>About</span>
          </Link>
        </li>
        <li className="nav-item">
          <Link 
            to="/portfolio" 
            className={`nav-link ${isActive('/portfolio') ? 'active' : ''}`}
          >
            <i className="fas fa-briefcase"></i>
            <span>Portfolio</span>
          </Link>
        </li>
        <li className="nav-item">
          <Link 
            to="/skills" 
            className={`nav-link ${isActive('/skills') ? 'active' : ''}`}
          >
            <i className="fas fa-code"></i>
            <span>Skills</span>
          </Link>
        </li>
        <li className="nav-item">
          <Link 
            to="/contact" 
            className={`nav-link ${isActive('/contact') ? 'active' : ''}`}
          >
            <i className="fas fa-envelope"></i>
            <span>Contact</span>
          </Link>
        </li>
      </ul>

      <div className="sidebar-footer">
        <div className="social-links">
          <a href="https://github.com" className="social-link" aria-label="GitHub" target="_blank" rel="noopener noreferrer">
            <i className="fab fa-github"></i>
          </a>
          <a href="https://linkedin.com" className="social-link" aria-label="LinkedIn" target="_blank" rel="noopener noreferrer">
            <i className="fab fa-linkedin"></i>
          </a>
          <a href="https://twitter.com" className="social-link" aria-label="Twitter" target="_blank" rel="noopener noreferrer">
            <i className="fab fa-twitter"></i>
          </a>
        </div>
      </div>
    </nav>
  )
}

export default Sidebar

// portfolio-angular/src/app/shared/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.scss'
})
export class SidebarComponent {
  isCollapsed = false;

  toggleSidebar() {
    this.isCollapsed = !this.isCollapsed;
  }
}

<nav class="sidebar" [class.collapsed]="isCollapsed">
  <div class="sidebar-header">
    <div class="logo">
      <i class="fas fa-snowflake"></i>
      <span>Good day, visitor!</span>
    </div>
    <button 
      class="sidebar-toggle" 
      (click)="toggleSidebar()" 
      aria-label="Toggle sidebar">
      <i class="fas fa-chevron-left" [class.rotated]="isCollapsed"></i>
    </button>
  </div>
  
  <ul class="nav-menu">
    <li class="nav-item">
      <a 
        routerLink="/home" 
        class="nav-link" 
        routerLinkActive="active"
        data-page="home">
        <i class="fas fa-home"></i>
        <span>Home</span>
      </a>
    </li>
    <li class="nav-item">
      <a 
        routerLink="/about" 
        class="nav-link" 
        routerLinkActive="active"
        data-page="about">
        <i class="fas fa-user"></i>
        <span>About</span>
      </a>
    </li>
    <li class="nav-item">
      <a 
        routerLink="/portfolio" 
        class="nav-link" 
        routerLinkActive="active"
        data-page="portfolio">
        <i class="fas fa-briefcase"></i>
        <span>Portfolio</span>
      </a>
    </li>
    <li class="nav-item">
      <a 
        routerLink="/skills" 
        class="nav-link" 
        routerLinkActive="active"
        data-page="skills">
        <i class="fas fa-code"></i>
        <span>Skills</span>
      </a>
    </li>
    <li class="nav-item">
      <a 
        routerLink="/contact" 
        class="nav-link" 
        routerLinkActive="active"
        data-page="contact">
        <i class="fas fa-envelope"></i>
        <span>Contact</span>
      </a>
    </li>
  </ul>

  <div class="sidebar-footer">
    <div class="social-links">
      <a href="https://github.com" class="social-link" aria-label="GitHub" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="https://linkedin.com" class="social-link" aria-label="LinkedIn" target="_blank">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="https://twitter.com" class="social-link" aria-label="Twitter" target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
    </div>
  </div>
</nav>
